# 解决windows下运行时无法识别主机名的问题
spring:
  application:
    name: cloud-admin
  boot:
    admin:
      client:
        prefer-ip: true
  security:
    user:
      name: blade1988
      password: blade1988
    basic:
      enabled: false


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS

logging:
  path: logs/log


#定义各种额外的详情给服务端显示
#从pom.xml中获取
info:
  app:
    name: "@project.name@"
    encoding: "@project.build.sourceEncoding@"
    java: "@java.version@"
  description: "@project.description@"
  version: "@project.version@"
  spring-boot-version: "@project.parent.version@"
