eureka:
  client:
    serviceUrl:
      defaultZone: ${saas.server-center.url}/eureka/
    enabled: ${saas.server-center.enabled}
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true

