server:
  port: 8761

eureka:
  instance:
    hostname: discovery
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:${server.port}/eureka/

spring:
  cloud:
    config:
      discovery:
        enabled: false