spring:
  datasource:
    activiti:
       url: jdbc:mysql://localhost:3306/activity?useUnicode=true&characterEncoding=utf8&useSSL=false
       username: root
       password: 123456
       driverClassName: com.mysql.jdbc.Driver
       type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    org:
      springframework:
        web: INFO                    #日志级别
  file: D:/logs/saas-dfa/adsfa.log  #日志地址
  config: classpath:logback-root.xml