
server:
  port: 8070

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.6:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
