eureka:
  client:
    serviceUrl:
      defaultZone: ${saas.server-center.url}/eureka/
    enabled: ${saas.server-center.enabled}
  instance:
    preferIpAddress: true

spring:
  application:
    name: zuul-gateway